name: flutter_sabak_04
description: "Dice app written in Flutter"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9

flutter:

 
  uses-material-design: true

 
  assets:
    - assets/dice-1.png
    - assets/dice-2.png
    - assets/dice-3.png
    - assets/dice-4.png
    - assets/dice-5.png
    - assets/dice-6.png


